name: Lint Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - run: npm i -g @antfu/ni

      - name: Install Dependencies
        run: ni --frozen

      - name: Run Lint
        run: nr lint
